---
title: "Storyboard Commentary"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    theme:
      version: 4
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
library(flexdashboard)
library(dplyr)
library(tidytext)
library(ggplot2)
library(tidyr)
library(readr)
library(topicmodels)
library(wordcloud)
library(leaflet)


news <- read_csv('news_sample.csv')
head(news)

news_df <- news %>%
  mutate(id = 1:nrow(news)) %>%
  select(id, text, reliable)

top_words <- news_df %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(id, word, reliable) %>%
  summarize(n = n())

top_words_reliable <- top_words %>%
  filter(reliable == 1)

top_words_unreliable <- top_words %>%
  filter(reliable == 0)
```


### News Sentiment: Reliable vs. Unreliable.  We can include a longer description here as well...



```{r}
top_words <- news_df %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(id, word, reliable) %>%
  summarize(n = n()) %>%
  group_by(reliable) %>%
  slice_max(n, n = 20) %>%
  mutate(reliable = recode(reliable, "1" = "Reliable", "0" = "Unreliable"))

ggplot(top_words, aes(x = n, y = reorder(word, n))) + geom_bar(stat = 'identity') + theme_minimal() +
  facet_wrap(~reliable) + ylab('')
```


*** 

Some commentary on the chart here...


### Sentiment Comparison: here we compare the sentiment of the "real" and "fake" news source.

```{r}
article_counts <- news_df %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

article_sentiment <- article_counts %>%
  inner_join(get_sentiments("afinn"))

news_sentiment_reliable <- article_sentiment %>%
  group_by(id, reliable) %>%
  summarize(sentiment = sum(value))

ggplot() +
  geom_density(data = news_sentiment_reliable[news_sentiment_reliable$reliable == 1,], aes(x = sentiment, fill = 'Reliable'), color = NA,  alpha = .5) + 
  geom_density(data = news_sentiment_reliable[news_sentiment_reliable$reliable == 0,], aes(x = sentiment, fill = 'Unreliable'), color = NA, alpha = .5) +
  theme_minimal() + scale_fill_manual(name = "", values = c("Reliable" = "purple", "Unreliable" = "orange"))
```

*** 

Deeper commentary about this chart here...

### And you can even do interactive things like maps! (more on this in the next couple lessons)

```{r}
leaflet() %>% addProviderTiles(providers$Esri.WorldImagery) %>% setView(lng = -73.95481621314316, lat = 41.389430881835274, zoom = 18)
```



