---
title: "Text Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      version: 4
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
library(flexdashboard)
library(dplyr)
library(tidytext)
library(ggplot2)
library(tidyr)
library(readr)
library(topicmodels)
library(wordcloud)


news <- read_csv('news_sample.csv')
head(news)

news_df <- news %>%
  mutate(id = 1:nrow(news)) %>%
  select(id, text, reliable)

top_words <- news_df %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(id, word, reliable) %>%
  summarize(n = n())

top_words_reliable <- top_words %>%
  filter(reliable == 1)

top_words_unreliable <- top_words %>%
  filter(reliable == 0)
```

Column {data-width=650}
-----------------------------------------------------------------------

### News Sentiment: Reliable vs. Unreliable

Here we could put some text to explain our charts...

```{r}
top_words <- news_df %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(id, word, reliable) %>%
  summarize(n = n()) %>%
  group_by(reliable) %>%
  slice_max(n, n = 20) %>%
  mutate(reliable = recode(reliable, "1" = "Reliable", "0" = "Unreliable"))

ggplot(top_words, aes(x = n, y = reorder(word, n))) + geom_bar(stat = 'identity') + theme_minimal() +
  facet_wrap(~reliable) + ylab('')
```

Column {data-width=350}
-----------------------------------------------------------------------

### Reliable News

```{r}
wordcloud(words = top_words_reliable$word, freq = top_words_reliable$n, min.freq = 1, max.words = 100,
          random.order = FALSE, rot.per = .35, colors = brewer.pal(8, 'Dark2'))

```

### Unreliable News

```{r}
wordcloud(words = top_words_unreliable$word, freq = top_words_unreliable$n, min.freq = 1, max.words = 100,
          random.order = FALSE, rot.per = .35, colors = brewer.pal(8, 'Dark2'))

```

